-- This file is not executed by any tooling and is retained only as a placeholder.
-- The authoritative schema is the embedded migrationSQL in internal/model/db.go,
-- applied automatically by model.Open.
